# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 0 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Daniele Pozzobon

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Stylish Jekyll Theme
author:
  name: Daniele Pozzobon
  email: dnl.pozzobon@gmail.com
  github: danielepo
  twitter: pozzobondaniele
  
  linkedin: danielepozzobon
  bio: I help enterprises reduce the cost of ownership of their software
  email_md5: a2eaf2964ffd1ef2b92c8119f5d868b2

  skills: [
    "C#", "JavaScript", "TypeScript", "F#", "Azure"
  ]
#rss_path: feed.xml
#categories_path: categories.html
#tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1



BASE_PATH:

gems:
  - jekyll-paginate
